@hostname = http://localhost:9000/api

### INSCRIPTION

POST {{hostname}}/subscribe
content-type: application/json

{
	"firstname": "Paul",
   "lastname": "Guy",
   "email": "paul@gmail.com",
   "password": "password"
}

### CONNECTION

POST {{hostname}}/login
content-type: application/json

{
   "email": "paul@gmail.com",
   "password": "password"
}

### CREER LISTE

POST {{hostname}}/user/1/list
content-type: application/json

{
   "name": "duda",
   "position": 9
}

### MODIFIER LISTE

PATCH {{hostname}}/user/1/list
content-type: application/json

{
   "id": 8,
   "name": "yes",
   "position": 3
}

### SUPPRIMMER LISTE

DELETE {{hostname}}/user/2/list
content-type: application/json

{
   "id": 7
}

### FETCH LISTE

GET {{hostname}}/user/2/list
content-type: application/json

