@hostname = http://localhost:9000/api

### séparateur entre deux requêtes

POST {{hostname}}/subscribe
content-type: application/json

{
	"firstname": "Corentin",
   "lastname": "Vanaquer",
   "email": "corentin@gmail.com",
   "password": "password"
}

### séparateur entre deux requêtes

POST {{hostname}}/login
content-type: application/json

{
   "email": "corentin@gmail.com",
   "password": "password"
}